with open('cook_book.txt', 'w', encoding='utf-8') as file:
    file.write('Омлет \n')
    file.write('3 \n')
    file.write('Яйцо | 2 | шт \n')
    file.write('Молоко | 100 | мл \n')
    file.write('Помидор | 2 | шт \n')
    file.write(' \n')
    file.write('Утка по-пекински \n')
    file.write('4 \n')
    file.write('Утка | 1 | шт \n')
    file.write('Вода | 3 | л \n')
    file.write('Мед | 3 | ст.л \n')
    file.write('Соевый соус | 60 | мл \n')
    file.write(' \n')
    file.write('Запеченный картофель \n')
    file.write('3 \n')
    file.write('Картофель | 1 | кг \n')
    file.write('Чеснок | 3 | зубч \n')
    file.write('Сыр гауда | 100 | г \n')
    file.write(' \n')
    file.write('Фахитос \n')
    file.write('5 \n')
    file.write('Говядина | 500 | г \n')
    file.write('Перец сладкий | 1 | шт \n')
    file.write('Лаваш | 2 | шт \n')
    file.write('Винный уксус | 1 | ст.л \n')
    file.write('Помидор | 2 | шт \n')
    file.write(' \n')

with open('cook_book.txt', 'r', encoding='UTF-8') as file:
    print(file)
